---
title: "課堂練習"
date: "9/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("/Users/anthonywwetterer/anaconda3/envs/m-team/bin/python",
           required = T)
use_condaenv("m-team", required = T)
```



# dictionary

```{python}
dictionaryA={
  "日期": [2001,2002,2003],
  "金額": [21000,33000,45880]}
dictionaryA

dictionaryA["數量"]=[100,200,300] # 增加新的 key-value pair
dictionaryA
```

```{python}
dictionaryA["日期"] # 查詢
```



```{python}
dictionaryA.keys()
```


```{python}
import requests
response=requests.get("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=3")
danceInfo=response.json()
```

```{python}
type(danceInfo)
```

```{python}
type(danceInfo[1])
```

```{python}
danceInfo[1].keys()
```


```{python}
danceInfo[1].values()
```



```{python}
dictionaryA.keys()
dictionaryA.values()
dictionaryA.items()

#dictionaryA.keys()[0]
list(dictionaryA.keys())
list(dictionaryA.values())
```

```{python}
dictionaryA.keys()
list(dictionaryA.keys())[0]
```

```{python}
dictionaryA.items()
list(dictionaryA.items())
```

```{python}
list(dictionaryA)
```

```{python}
import pandas as pd

finStatement=pd.read_csv("http://mopsfin.twse.com.tw/opendata/t187ap06_O_ci.csv")
dict_finStatement=finStatement.to_dict()
```

```{r}
#library(dplyr)
View(py$dict_finStatement)
```

```{python}
dict_finStatement.keys()
```


```{python}
dict_finStatement.get( '營業利益（損失）').values()
dict_finStatement.get('公司名稱')
```

1. 找出損失的index
```{python}
profit=list(dict_finStatement.get( '營業利益（損失）').values())

lossFirmKeys=[index for index in range(len(profit)) if profit[index]<0]
```

2. 由index進去公司找出名稱
```{python}
index=lossFirmKeys[100]
dict_finStatement.get('公司名稱')[index]
dict_finStatement.get('公司名稱').get(index)

[dict_finStatement.get('公司名稱').get(index) for index in lossFirmKeys]
```

dictionary comprehension 呈現公司名稱：損失金額
```{python}
{dict_finStatement.get('公司名稱').get(index): list(dict_finStatement.get( '營業利益（損失）').values())[index] for index in lossFirmKeys}
```

```{python}
dict_finStatement.get( '營業利益（損失）').values()
```

```{python}
[dict_finStatement["公司名稱"][i]  
  for i in range(len(dict_finStatement["營業利益（損失）"] )) 
  if dict_finStatement["營業利益（損失）"][i] < 0]
```


# comprehension with condition

```{python}
listA=[10,2,7,3,8]

[listA[index] for index in range(len(listA)) if listA[index]>5]
[index for index in range(len(listA)) if listA[index]>5 ]
```

# Functions

```{python}
def myFun(x,y):
  z=x+y
  return z
  
myFun(5,6)
myFun(0,1)

def myFun2(x,y):
  return x+y

myFun2(5,6)
myFun2(0,1)
```

```{python}
def myFun3(x,y=6):
  return x+y
  
myFun3(x=5,y=6)
myFun3(5)
```

## packing/unpacking

```{python}
listA=(0,1,3)

a,b,c=listA # def  ...(a,b,c)
a
b
c

a,*b=listA # def ...(a,*b)
a
b
```

```{python}
# (0,alpha=1,beta=3)

# def ...(a,**b)
```

b=

```{python}
b={"alpha": 1, "beta": 3}
```

```{python}
def test(input1, input2=0):
  print('input1 is ', input1)
  print('input2 is ', input2)
  return None
  
test(1,1) 
test(input1=1,input2=1)

test(1) # 動用到預設值
```

## pack to tuple

```{python}
def test2(input1,*input3):
  print('input1 is ', input1)
  print('input3 is ', input3)
  return None
 
test2(1,1.2,4,5)
test2(1,[1.2,4],5)
test2(["1","b"],{2,5,7},10)
```

```{python}
input1, *input3=(1, 1.2, 4, 5)
input1, *input3=(1,[1.2,4],5)
input1, *input3=(["1","b"],{2,5,7},10)
```

```{python}
x, *seq, y=(1,2,3,4,5)
```

```{python}
def f(x, *seq, y):
    print("x is: ", x)
    print("seq is: ", seq)
    print("y is: ", y)
    return None

f(1, 2, 3, 4, 5)
f(1, 2, 3, 4, y=5)
```

```{python}
a, b, c=(1,3,4)
a, b, c=(*[1,3],4)
a, b, c=(1,*[3,4])
a, b, c=(*[1,3,4])

```

```{python}
utility_cobb_douglas(1,1,alpha=0.5,beta=0.5)
```

```{python}
x, y, **parameters  =(1,1,alpha=0.5,beta=0.5)
```

```{python}
parameters={
"alpha": 0.5,
"beta": 0.5
}
```



```{python}
def utility_cobb_douglas(x, y, **parameters):
  alpha=parameters["alpha"]
  beta=parameters["beta"]
  utilValue = x**alpha*y**beta 
  return utilValue # 傳回output值

```

# local global environment

```{python}
obj2
obj3
::
::
# call objX=utility_cobb_douglass(1,1,alpha=0.5,beta=0.5)
  x,y,alpha,beta=(1,1,0.5,0.5)
  utilValue = x**alpha*y**beta 
  return utilValue

```

```{python}
global1=[1,3,[4,5]]

def funtest(x):
  x[0]="a"
  y=x[:]
  y[1]="b"
  y[2][1]="c"
  return None

global1
funtest(global1) #call
global1
```

# executive environment of funtest(global1)
```{python}
global1=[1,3,[4,5]]

global1

# enter executive environment
x=global1
x[0]="a"
y=x[:]
y[1]="b"
y[2][1]="c"

# kill executive environment objects
del x, y
global1
```


```{python}
global1=[1,3,[4,5]]
def funtest(x):
  x[0]="a"
  y=x[:]
  y[1]="b"
  y[2][1]="c"
  return None

global1
funtest(global1)
global1
```


```{python}
def utility_cobb_douglass(x,y,alpha=1,beta=3):
  
  utilValue = x**alpha*y**beta*obj3 # 程序產生output值
  
  return utilValue # 傳回output值

utility_cobb_douglass(1,1,0.5,0.5)
utility_cobb_douglass(1,1)
```



```{python}
global1=[1,3,[4,5]]
funtest(global1.copy())
global1

import copy 
global1=[1,3,[4,5]]
funtest(copy.deepcopy(global1))
global1
```


```{python}
def test(x,y):
  return x+y+obj3

obj3=5

test(1,4)
```

