---
title: "課堂練習"
date: "9/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("/anaconda3/envs/m-team/bin/python",
           required = T)
use_condaenv("m-team", required = T)
```

```{r}
print(Sys1)
```



# 7

```{python}
Omega_2={
    ("h","h"),("h","t"),("t","h"),("t","t")}  

print(Omega_2)
```

```{python}
Omega_2b={
    ["h","h"],["h","t"],["t","h"],["t","t"]}  
```

比較list and tuple
```{python}
["h","h"].append("h")
("h","h").count("h")
```

subset
```{python}
# subset
Omega_2

{('t','h')}.issubset(Omega_2)
{('t', 'h'), ('h', 'h')}.issubset(Omega_2)
set([]).issubset(Omega_2) # 空集合 (empty set/ null set)
Omega_2.issubset(Omega_2) # sample space itself
```

{('t','h')}.issubset(Omega_2) => True
{('t', 'h'), ('h', 'h')}.issubset(Omega_2) => True

```{python}
event_space={
frozenset({('t','h')}),
frozenset({('t', 'h'), ('h', 'h')}),
}
```

```{python}
import itertools
```

```{python}
A_big=set([frozenset([]),frozenset(Omega_2)])
print(A_big)
```

```{python}
maxN=len(Omega_2)
for outcomeNumber in range(1,maxN):
    for ix in itertools.combinations(Omega_2, outcomeNumber): # (1)
        A_big.add(frozenset(ix))

print(A_big)
```


Probability measure
```{python}
import pandas as pd
import numpy as np
Pt=0.5  # probability of tail
Omega_2_a=np.array(list(Omega_2))
Omega_2_a
```

```{python}
Omega_2_a
Omega_2_a[:,0]=='h'
Omega_2_a[:,1]=='h'
```


```{python}
Pt=0.5
Omega_2_a[:,0]=='t'
Pt**(Omega_2_a[:,0]=='t')
```

Pt**(Omega_2_a[:,0]=='t') is equal to 
$$
Pt**\left[\begin{array}{c}
F\\
T\\
T\\
F
\end{array}\right]=\left[\begin{array}{c}
Pt**F\\
Pt**T\\
Pt**T\\
Pt**F
\end{array}\right]=\left[\begin{array}{c}
Pt**0\\
Pt**1\\
Pt**1\\
Pt**0
\end{array}\right]
$$

```{python}
(1-Pt)**(Omega_2_a[:,0]=='h')
```


```{python}
P_omega=Pt**(Omega_2_a[:,0]=='t')*(1-Pt)**(1-(Omega_2_a[:,0]=='t'))*Pt**(Omega_2_a[:,1]=='t')*(1-Pt)**(1-(Omega_2_a[:,1]=='t')) # [1]
```

```{python}
P_omega
```

```{python}
P_omega=pd.Series(P_omega, index=Omega_2_a)
print(P_omega)
```

```{python}
event_test=frozenset({('h', 't'), ('h', 'h')})
print(event_test)
```

# pandas index

```{python}
P_omega.index
P_omega[[('h','t')]]
P_omega[[('h','t'),('h','h')]]
```

```{python}
list(event_test)
P_omega[list(event_test)]
```


```{python}
P_omega.index
P_omega[[('h', 't')]]
P_omega[[('h','t'),('t','h')]].sum()
```

probability function
```{python}
def P(A, Pt=0.5):
    Omega_2_a=np.array(list(Omega_2))
    P_omega=Pt**(Omega_2_a[:,0]=='t')*(1-Pt)**(1-(Omega_2_a[:,0]=='t'))*Pt**(Omega_2_a[:,1]=='t')*(1-Pt)**(1-(Omega_2_a[:,1]=='t')) # (1)
    P_omega=pd.Series(P_omega, index=Omega_2_a)
    return sum(P_omega[list(A)])


```

```{python}
P(event_test,0.8)
```

```{python}
A_big_list=list(A_big)
A_big_list[0]
P(A_big_list[0])
A_big_list[10]
P(A_big_list[10])
```

```{python}
probability_space_2t={
    "sample space": Omega_2,
    "event space" : A_big,
    "probability" : P
}
```

```{python}
dict_grade={
    '學號': [172,214,322,425,517],
    '姓名': ["小明","大雄","胖虎","小新","大白"],
    '成績': [80,60,90,70,50]
}

df_grade0=pd.DataFrame(dict_grade)
```

